apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "chart.fullname" . }}-init
  labels:
    app.kubernetes.io/name: {{ include "chart.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    # This is what defines this resource as a hook. Without this line, the
    # job is considered part of the release.
    "helm.sh/hook": post-install,post-upgrade
    "helm.sh/hook-weight": "-5"
    "helm.sh/hook-delete-policy": hook-succeeded    
spec:
  template:
    spec:
      containers:
      - name: lifemonitor-init
        image: {{ include "chart.lifemonitor.image" . }}
        imagePullPolicy: {{ .Values.lifemonitor.imagePullPolicy }}
        command:
        - /bin/sh
        - -c
        - |
          wait-for-redis.sh \
          && wait-for-postgres.sh \
          && ./lm-admin db init \
          && ./lm-admin task-queue reset
        env:
        {{- include "lifemonitor.common-env" . | nindent 10 }}
        volumeMounts:
        {{- include "lifemonitor.common-volume-mounts" . | nindent 10 }}
      restartPolicy: OnFailure
      volumes:
        {{- include "lifemonitor.common-volume" . | nindent 8 }}
       {{- with .Values.lifemonitor.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.lifemonitor.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}        
      {{- end }}
  backoffLimit: 4
